### ISSUE TITLE
No Applet in swaywm

### ISSUE THREAD

**Issue by scharc** [jaspwr/vol-applet#4]
I have a brand new ubuntu 23.10 with swaywm / wayland installed. I installed all deps with 
```
sudo apt install -y cargo pkg-config
sudo apt install -y libgtk-3-dev --no-install-recommends
git clone https://github.com/jaspwr/vol-applet
cd vol-applet
cargo build --release
```
If I start the application I only get 
```
(volapplet:40845): Gtk-CRITICAL **: 21:52:07.406: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(volapplet:40845): Gtk-CRITICAL **: 21:52:07.409: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(volapplet:40845): Gtk-CRITICAL **: 21:52:07.409: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```
My setup:
```
>_ inxi -G
Graphics:
  Device-1: NVIDIA TU116 [GeForce GTX 1660 Ti] driver: nouveau v: kernel
  Display: wayland server: X.org v: 1.21.1.7 with: Xwayland v: 23.2.0
    compositor: sway v: 1.8.1 driver: X: loaded: modesetting
    unloaded: fbdev,vesa dri: nouveau gpu: nouveau resolution:
    1: 3440x1440~75Hz 2: 1920x1080~60Hz
  API: OpenGL v: 4.3 Mesa 23.2.1-1ubuntu3 renderer: NV168
```

any suggestions?
